File copied : /root/sailfish/code/static_analysis/analysis/RC.sol
processing /root/sailfish/code/static_analysis/analysis/RC.sol
Installing solc '0.4.26'...
Version '0.4.26' installed.
Switched global version to 0.4.26
[INFO] | 2023-12-05 02:35:03 AM | analyzer.RC     | Analysis started at: 2023-12-05 02:35:03 AM
[INFO] | 2023-12-05 02:35:05 AM | analyzer.RC     | Version constraints: ['^0.4.19']
[INFO] | 2023-12-05 02:35:05 AM | analyzer.RC     | solc version: v0.4.19
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/platform/solc.py", line 368, in _run_solc
    ret = json.loads(stdout)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.8-py3.6.egg/slither/slither.py", line 60, in __init__
    crytic_compile = CryticCompile(target, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/crytic_compile.py", line 137, in __init__
    self._compile(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/crytic_compile.py", line 987, in _compile
    self._platform.compile(self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/platform/solc.py", line 152, in compile
    force_legacy_json=force_legacy_json,
  File "/usr/local/lib/python3.6/dist-packages/crytic_compile/platform/solc.py", line 372, in _run_solc
    raise InvalidCompilation(f"Invalid solc compilation {stderr}")
crytic_compile.platform.exceptions.InvalidCompilation: Invalid solc compilation /root/sailfish/code/static_analysis/analysis/RC.sol:66:30: Error: Expected token Semicolon got 'LParen'
    emit OwnershipTransferred(owner, newOwner);
                             ^
RC.sol:66:30: Error: Expected token Semicolon got 'LParen'
    emit OwnershipTransferred(owner, newOwner);
                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "contractlint.py", line 67, in analyze_contracts
    slither_obj = Slither(contract_path, solc=solc_path)
  File "/usr/local/lib/python3.6/dist-packages/slither_analyzer-0.6.8-py3.6.egg/slither/slither.py", line 63, in __init__
    raise SlitherError('Invalid compilation: \n'+str(e))
slither.exceptions.SlitherError: Invalid compilation: 
Invalid solc compilation /root/sailfish/code/static_analysis/analysis/RC.sol:66:30: Error: Expected token Semicolon got 'LParen'
    emit OwnershipTransferred(owner, newOwner);
                             ^
RC.sol:66:30: Error: Expected token Semicolon got 'LParen'
    emit OwnershipTransferred(owner, newOwner);
                             ^

[36m[#] Analysing started: RC.sol[0m
/root/.solc-select/artifacts/solc-0.4.26
9470444c0e8ce8b62f6dbf0ef91d7fb455182f08030d6e641861c72331aa0bf7
